### ISSUE TITLE
Reading Color from Image Palette instead Of from Color Usage

### ISSUE THREAD

**Issue by nolddor** [maxim-zhao/bmp2tile#6]
I've create a 4bpp image with this Palette using Grpahic Gale FreeEdition:
![graphicgale](https://cloud.githubusercontent.com/assets/1280022/10886947/c16a308e-8184-11e5-8800-beeca7711936.PNG)
Lasts 9 colors are unused, but i need them for share with other tiles...

When I use Bitmap2Tile the palette is reading from color usage instead of Internal Image Palette:
![captura](https://cloud.githubusercontent.com/assets/1280022/10887023/27c46b4c-8185-11e5-9749-154275b414b3.PNG)
So the generated Palette isn't the same as the image have.

**Comment by maxim-zhao** [comment]
This is by design, trying to avoid writing palette data that is not used. If you have a master image with all colours, use it to generate the palette data (you can discard its contents if you like). Then just make sure your various bitmaps share the exact same palette and all should work as intended.

Alternatively, you can put all your tiles on a single image. This can work when you are not interested in the tilemap data, and you want to have a "blank" tile anyway.

**Comment by sverx** [comment]
I guess Maxim just solved this issue too, see https://github.com/maxim-zhao/bmp2tile/issues/7 :)
